[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build]
rustflags = ["-C", "opt-level=0", "-C", "llvm-args=-x86-asm-syntax=intel"]
[dependencies]
